version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # - pip install -r requirements.txt -t lib
  build:
    commands:
      # - cd lib
      # - zip -r9 ../deployment_package.zip .
      # - cd ..
      - zip -g deployment_package.zip lambda_function.py
artifacts:
  files:
    - deployment_package.zip
  # post_build:
  #   commands:
  #     - aws lambda update-function-code --function-name tecemer-devops --zip-file fileb://deployment_package.zip
